### ISSUE TITLE
Theme running on Ubuntu

### ISSUE THREAD

**Issue by lynxmedeiros** [btd1337/Stupendously-Hot-Charmander#20]
I would like to congratulate everyone for the excellent theme, I already installed on _Ubuntu 16.04_ and also on _Ubuntu Minimal 17.10_ with Mate environment.
Being that in _Ubuntu 17.10_ with Mate, the Theme installed Unity, and in the login screen the user can choose which environment to use.
Greetings.

**Comment by btd1337** [comment]
I don't understand. Was that a question?

**Comment by Alzemand** [comment]
Close

**Comment by lynxmedeiros** [comment]
Do not.
I wanted to say to congratulate the project.

**Comment by btd1337** [comment]
Thanks bro!
