### ISSUE TITLE
broken layout

### ISSUE THREAD

**Issue by juniorthiesen** [btd1337/Stupendously-Hot-Charmander#3]
![captura de tela de 2016-06-20 14-52-21](https://cloud.githubusercontent.com/assets/9570006/16204595/006b48fa-36f6-11e6-8637-f7bc57375b6d.png)

broken layout - font color with problem

**Comment by btd1337** [comment]
At first, the theme is for **Unity** (Default Ubuntu Interface). It's not 100% compatible with Ubuntu Gnome.
