### ISSUE TITLE
Remove completely

### ISSUE THREAD

**Issue by mprandot** [btd1337/Stupendously-Hot-Charmander#4]
Hello!

I need remove completely this theme, how do this?

Thanks!

**Comment by btd1337** [comment]
It's not necessary remove this to return to the old state.

Open _Unity Tweak Tool_ and set the themes to the default state.

**Please don't remove before you go back to the old theme.**

To remove:

sudo rm -R /usr/share/themes/SH-Charmander
sudo rm -R /usr/share/icons/Charmander-Circle
sudo rm -R /usr/share/icons/Breeze
sudo rm -R /usr/share/backgrounds/bg_SHC_*
